check50:
  files: &check50_files
    - !exclude "*"
    - !include "*_bot.py"
    - !exclude "basic_bot.py"
    - !exclude "random_bot.py"
    - !exclude "intermediate_bot.py"

submit50:
  files: *check50_files
  style: false
